trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host Starting the synchronization process
      mkdir syncrepo
      $sourceURL = "https://${env:GITHUBTOKEN}@${env:GITHUBREPOPATH}"
      $destURL = "https://${env:DEVOPSTOKEN}@${env:DEVOPSREPOPATH}"
      Set-Location "$(Build.SourcesDirectory)/syncrepo"
      git clone --mirror $sourceURL
      Set-Location "$(Build.SourcesDirectory)/syncrepo/${env:REPONAME}/"
      Write-Host "*****Git removing remote origin****"
      git remote rm origin
      Write-Output "*****Git remote add****"
      git remote add --mirror=fetch origin $destURL
      Write-Output "*****Git fetch origin****"
      git fetch $sourceURL
      Write-Output "*****Git push to Azure Repos****"
      git push origin --all -f