name: Upstream Sync

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  sync_upstream:
    runs-on: ubuntu-latest
    name: Sync with Upstream
    
    steps:
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: main
    
    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
      with:
        target_sync_branch: main
        target_repo_token: ${{secrets.GITHUB_TOKEN}}
        upstream_sync_repo: jaozafra/Test
        upstream_sync_branch: main
        test_mode: false
    
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits found. Syncing."
      
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "No new commits."
